### ISSUE TITLE
Is there some reason that Fastly 2.4.0 is still used, rather than 3.7.0?

### ISSUE THREAD

**Issue by alex8bitw** [honojs/starter#17]
https://github.com/honojs/starter/blob/7a6bfc328ddc3856168cf9ae77293f34bf6cd93d/templates/fastly/package.json#L12C7-L12C8

**Comment by yusukebe** [comment]
Hi @alex8bitw 

No reason! We can upgrade it.

**Comment by alex8bitw** [comment]
Great!  I can confirm the latest version works just fine.

**Comment by alex8bitw** [comment]
I added a PR for another small change which I think is crucial.  https://github.com/honojs/starter/pull/18
