### ISSUE TITLE
Delete wrangler.toml from .gitignore

### ISSUE THREAD

**Issue by kasa021** [honojs/starter#23]
Hi, Honoer! Thank you for this wonderful project!

I melted a few hours to deploy due to wrangler.toml being gitignored. 
How about deleting wrangler.toml from .gitignore as it's unlikely I'll actually gitignore it?

**Comment by yusukebe** [comment]
Hi @kasa021 

> How about deleting wrangler.toml from .gitignore as it's unlikely I'll actually gitignore it?

I think we can remove `wrangler.toml` from `.gitignore`. If you don't mind, could you make a PR?

**Comment by kasa021** [comment]
ok!

**Comment by NicoPlyley** [comment]
@yusukebe Closed in 170c456

**Comment by yusukebe** [comment]
@NicoPlyley Yes. Closing.
