### ISSUE TITLE
chore: Use Bun as a package manager

### ISSUE THREAD

**Issue by goisaki** [honojs/starter#48]
I think we should use Bun instead of yarn in this repository too.
We are already using it in our main repositories Hono and HonoX.
> See also a similar completed Issue on Hono: https://github.com/honojs/hono/pull/2105

**Comment by yusukebe** [comment]
Hi @goisaki 

This repository is mainly used only by maintainers (almost me), so the package manager does not call many times. I'm satisfied with the `yarn` command ( I only need the `yarn up` command). This is not needed or is a low priority.
