### ISSUE TITLE
Refactor the deploy command for Cloudflare Workers templates

### ISSUE THREAD

**Issue by asahi-iwm** [honojs/starter#51]
I noticed this while trying out Workers Builds.  
This is just my proposal, and I would like to gather opinions and initiate a discussion.

When following the instructions on the Hono documentation to use Workers Builds with `npm create hono@latest my-app`, it doesn’t seem to work as expected.  
- https://hono.dev/docs/getting-started/cloudflare-workers

I propose the following changes to address the issue (I would like the Workers feature to be considered as well):
- Add `main = "src/index.ts"` to `wrangler.toml`.
- Update the deploy command in `package.json` to `“deploy”: “wrangler deploy --minify”`.

**Comment by yusukebe** [comment]
Hi @asahi-iwm 

Thank you for the issue. 100% agree. Could you create a PR?

**Comment by asahi-iwm** [comment]
@yusukebe 
Yes, of course.
I will prepare and create it.

**Comment by yusukebe** [comment]
@asahi-iwm Thank you!

**Comment by asahi-iwm** [comment]
@yusukebe 

I have created a PR.
This is my first OSS contribution, so please point out any deficiencies.

**Comment by yusukebe** [comment]
This is closed by #52
