### ISSUE TITLE
Vercel template serves unwanted project files

### ISSUE THREAD

**Issue by unixzii** [honojs/starter#56]
## Description

When creating new projects with Vercel template, project files (like `README.md`) are unexpectedly served.

The expected behavior should be that only APIs defined in `api/index.js` are exposed.

## Workaround

Modify `vercel.json` as follows:

```json
{
  "rewrites": [
    {
      "source": "/api/(.*)",
      "destination": "/api"
    }
  ],
  "builds": [
    {
      "use": "@vercel/node",
      "src": "api/index.ts",
      "config": { "zeroConfig": true }
    }
  ]
}
```

However `builds` field is deprecated, so I'm asking if there's a better solution.

**Comment by shakibhasan09** [comment]
I think you don't have public directory in your root directory. Just add the public directory with your assets. Then vercel won't show your root files.
