### ISSUE TITLE
Trailing comma in nodejs/tsconfig.json

### ISSUE THREAD

**Issue by Rewwoken** [honojs/starter#65]
There is a [trailing comma in Node.js template tsconfig.json](https://github.com/honojs/starter/blob/7e7622cd1e074bf4887114910b5a9818db9610ad/templates/nodejs/tsconfig.json#L12), is it correct?

**Comment by yusukebe** [comment]
@Rewwoken 

Yes, it's correct. The file format of `tsconfig.json` is "JSONC," which allows a trailing comment.
